version: '3.9'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    
  backend:
    depends_on:
      - db
    container_name: backend
    build: backend/
    ports:
      - 8081:8000
    environment:
      DB_NAME: 'backend'
      DB_HOST: 'db'
      DB_PORT: 5432
      DB_USERNAME: 'backend'
      DB_PASSWORD: '123456'
    volumes:
      - ./backend/server/detection/models:/app/server/detection/models

volumes:
  db_home:
    external: false